services:
  neo4j:
    image: neo4j:5.22
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=neo4j/supersecret
      - NEO4J_server_memory_heap_initial__size=512m
      - NEO4J_server_memory_heap_max__size=512m
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - neo4j_plugins:/plugins
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  s03e02_app:
    build: .
    container_name: s03e02_app
    depends_on:
      - qdrant
      - neo4j
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CENTRALA_URL=${CENTRALA_URL}
      - CENTRALA_SECRET=${CENTRALA_SECRET}
      - QDRANT_URL=http://qdrant:6333
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=neo4j
    volumes:
      - .:/app
    command: ["bun", "run", "tasks/S03E02/index.ts"]

  app_s03e05:
    build: .
    container_name: s03e05_app
    depends_on:
      - neo4j
    environment:
      - CENTRALA_URL=${CENTRALA_URL}
      - CENTRALA_SECRET=${CENTRALA_SECRET}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=supersecret
    volumes:
      - .:/app
    command: ["bun", "run", "tasks/S03E05/index.ts"]

  s04e04_app:
    build: .
    container_name: s04e04_app
    env_file: .env
    volumes:
      - .:/app
    command: ["bun", "run", "tasks/S04E04/server.ts"]

volumes:
  qdrant_storage:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  neo4j_plugins:


