version: '3.8'
services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
    volumes:
      - qdrant_storage:/qdrant/storage

  app:
    build: .
    container_name: s03e02_app
    depends_on:
      - qdrant
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - CENTRALA_URL=${CENTRALA_URL}
      - CENTRALA_SECRET=${CENTRALA_SECRET}
      - QDRANT_URL=http://qdrant:6333
    volumes:
      - .:/app
    command: ["bun", "run", "tasks/S03E02/index.ts"]

volumes:
  qdrant_storage:


